version: "3"

services:
  keycloak_learnix:
    image: quay.io/keycloak/keycloak:23.0
    volumes:
      - ./imports:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_svr
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_PASSWORD: ichlearnenix
      KC_DB_USERNAME: learnixandchill
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres_svr:
        condition: service_healthy

  postgres_svr:
    image: postgres:14.2
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: '"keycloakdb","learnixdb"'
      POSTGRES_USER: learnixandchill
      POSTGRES_PASSWORD: ichlearnenix

    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
